### ISSUE TITLE
MaxFileCount in List_file_versions

### ISSUE THREAD

**Issue by acidburn23** [mtingers/backblaze-b2#8]
At present, the list_filr_versions returns first 100 files I tried the following thing to get more files in single call 
`    def list_file_versions(self, bucket_id=None, bucket_name=None, max_file_account=None):
        bucket = self.get_bucket_info(bucket_id=bucket_id,
                                      bucket_name=bucket_name)
        self._authorize_account()
        return self._api_request(
            '%s/b2api/v1/b2_list_file_versions' % self.api_url,
            {'bucketId': bucket['bucketId'],
             'maxFileCount': max_file_account},
            {'Authorization': self.authorization_token})
`
When passing the following command:
`file_names = b2.list_file_versions(bucket_name='abc', max_file_account='20')`

It returns the error HTTP Error 400: Bad request. I was wondering if there a way to pass more parameters it the Http message body?

**Comment by hinterlandcreative** [comment]
I just put a PR up that adds these features you're welcome to use it in the meantime until it's approved.

**Comment by acidburn23** [comment]
Thanks Appreciated

**Comment by mtingers** [comment]
@acidburn23 Thanks of the report. 
@hinterlandsupplyco Thanks for the PR -- it has been merged. Let me know if you have any issues as it did have a conflict that was manually resolved.
